from collections.abc import Sequence

class CryptContext:
    def __init__(self, schemes: Sequence[str], deprecated: str = ...) -> None: ...
    def verify(self, secret: str, hash: str) -> bool: ...
    def hash(self, secret: str) -> str: ...
