from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path
from typing import Any

try:
    from scripts.streaming.live_consistency_common import to_float, to_int
except ModuleNotFoundError:  # pragma: no cover - direct script execution fallback
    from live_consistency_common import to_float, to_int


PERCENTILE_FIELDS = ("p50_ms", "p95_ms", "p99_ms")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate live_1000_consistency run report.")
    parser.add_argument(
        "--report",
        type=str,
        default="benchmarks/results/streaming/live_1000_consistency.json",
        help="Path to report generated by scripts/streaming/run_live_1000_consistency.py",
    )
    parser.add_argument(
        "--expected-stream-loops",
        type=int,
        default=0,
        help="Expected stream loop count (0 uses report config).",
    )
    parser.add_argument(
        "--expected-stress-runs",
        type=int,
        default=0,
        help="Expected stress run count (0 uses report config).",
    )
    parser.add_argument(
        "--max-error-rate-percent",
        type=float,
        default=0.0,
        help="Maximum allowed error rate percent per stress metric, per run.",
    )
    parser.add_argument(
        "--max-p50-drift-pct",
        type=float,
        default=100.0,
        help="Maximum allowed per-metric drift from median for p50.",
    )
    parser.add_argument(
        "--max-p95-drift-pct",
        type=float,
        default=120.0,
        help="Maximum allowed per-metric drift from median for p95.",
    )
    parser.add_argument(
        "--max-p99-drift-pct",
        type=float,
        default=150.0,
        help="Maximum allowed per-metric drift from median for p99.",
    )
    parser.add_argument(
        "--out",
        type=str,
        default="",
        help="Optional path to write check output JSON.",
    )
    return parser.parse_args()


def _load_report(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return payload if isinstance(payload, dict) else {}


def _max_deviation_pct(values: list[float]) -> float:
    if len(values) <= 1:
        return 0.0
    baseline = statistics.median(values)
    if baseline == 0.0:
        return 0.0 if max(abs(value) for value in values) == 0.0 else float("inf")
    return max(abs(value - baseline) / abs(baseline) * 100.0 for value in values)


def _validate_stream(
    stream: dict[str, Any],
    expected_loops: int,
    issues: list[str],
) -> dict[str, Any]:
    if not bool(stream.get("enabled")):
        return {"enabled": False}

    if to_int(stream.get("return_code"), default=1) != 0:
        issues.append("stream_gate:return_code_nonzero")
    summary = stream.get("summary") if isinstance(stream.get("summary"), dict) else {}
    scenarios = summary.get("scenarios") if isinstance(summary.get("scenarios"), list) else []
    if not scenarios:
        issues.append("stream_gate:no_scenarios")

    scenario_results: list[dict[str, Any]] = []
    for row in scenarios:
        if not isinstance(row, dict):
            continue
        scenario_id = str(row.get("scenario_id") or "")
        runs = to_int(row.get("runs"), default=0)
        if expected_loops > 0 and runs != expected_loops:
            issues.append(f"stream_gate:{scenario_id}:runs_mismatch expected={expected_loops} actual={runs}")
        status_counts = row.get("status_counts") if isinstance(row.get("status_counts"), dict) else {}
        non_pass = {k: to_int(v, default=0) for k, v in status_counts.items() if str(k) != "PASS" and to_int(v, 0) > 0}
        if non_pass:
            issues.append(f"stream_gate:{scenario_id}:non_pass_statuses={non_pass}")
        law_checker_failures = to_int(row.get("law_checker_failures"), default=0)
        if law_checker_failures > 0:
            issues.append(f"stream_gate:{scenario_id}:law_checker_failures={law_checker_failures}")
        min_expected = to_int(row.get("min_expected_token_deltas"), default=0)
        token_min = to_int(row.get("token_delta_min"), default=0)
        if min_expected > 0 and token_min < min_expected:
            issues.append(
                f"stream_gate:{scenario_id}:token_delta_min_below_expected expected_min={min_expected} actual={token_min}"
            )
        terminal_values = row.get("terminal_event_values") if isinstance(row.get("terminal_event_values"), list) else []
        if len(terminal_values) > 1:
            issues.append(f"stream_gate:{scenario_id}:terminal_event_drift={terminal_values}")
        commit_values = row.get("commit_outcome_values") if isinstance(row.get("commit_outcome_values"), list) else []
        if len(commit_values) > 1:
            issues.append(f"stream_gate:{scenario_id}:commit_outcome_drift={commit_values}")
        scenario_results.append(
            {
                "scenario_id": scenario_id,
                "runs": runs,
                "non_pass_statuses": non_pass,
                "law_checker_failures": law_checker_failures,
                "token_delta_min": token_min,
                "token_delta_expected_min": min_expected,
                "terminal_event_values": terminal_values,
                "commit_outcome_values": commit_values,
            }
        )

    return {
        "enabled": True,
        "expected_loops": expected_loops,
        "scenario_count": len(scenario_results),
        "scenario_results": scenario_results,
    }


def _validate_stress(
    stress: dict[str, Any],
    expected_runs: int,
    max_error_rate_percent: float,
    max_drift_pct: dict[str, float],
    issues: list[str],
) -> dict[str, Any]:
    if not bool(stress.get("enabled")):
        return {"enabled": False}

    runs = stress.get("run_summaries") if isinstance(stress.get("run_summaries"), list) else []
    runs_completed = len(runs)
    if expected_runs > 0 and runs_completed != expected_runs:
        issues.append(f"stress:runs_mismatch expected={expected_runs} actual={runs_completed}")

    metric_names: set[str] = set()
    for run in runs:
        metrics = run.get("metrics") if isinstance(run.get("metrics"), dict) else {}
        metric_names.update(metrics.keys())
        run_index = to_int(run.get("index"), default=0)
        if to_int(run.get("return_code"), default=1) != 0:
            issues.append(f"stress:run_{run_index:04d}:return_code_nonzero")
        for metric_name, metric in metrics.items():
            if not isinstance(metric, dict):
                issues.append(f"stress:run_{run_index:04d}:{metric_name}:invalid_metric_payload")
                continue
            failures = to_int(metric.get("failures"), default=0)
            error_rate = to_float(metric.get("error_rate_percent"), default=0.0)
            if failures > 0:
                issues.append(f"stress:run_{run_index:04d}:{metric_name}:failures={failures}")
            if error_rate > max_error_rate_percent:
                issues.append(
                    f"stress:run_{run_index:04d}:{metric_name}:error_rate_exceeded "
                    f"actual={error_rate:.4f} allowed={max_error_rate_percent:.4f}"
                )

    drift_summary: dict[str, Any] = {}
    for metric_name in sorted(metric_names):
        per_metric: dict[str, Any] = {}
        for field in PERCENTILE_FIELDS:
            values: list[float] = []
            for run in runs:
                metrics = run.get("metrics") if isinstance(run.get("metrics"), dict) else {}
                metric = metrics.get(metric_name) if isinstance(metrics.get(metric_name), dict) else {}
                value = metric.get(field)
                if value is None:
                    continue
                values.append(to_float(value, default=0.0))
            drift_pct = _max_deviation_pct(values)
            allowed = float(max_drift_pct[field])
            if drift_pct > allowed:
                issues.append(
                    f"stress:{metric_name}:{field}:drift_exceeded actual={drift_pct:.4f}% allowed={allowed:.4f}%"
                )
            per_metric[field] = {
                "samples": len(values),
                "median": round(statistics.median(values), 3) if values else None,
                "max_deviation_pct": round(drift_pct, 4),
                "allowed_pct": round(allowed, 4),
            }
        drift_summary[metric_name] = per_metric

    return {
        "enabled": True,
        "expected_runs": expected_runs,
        "runs_completed": runs_completed,
        "metric_count": len(metric_names),
        "drift_summary": drift_summary,
    }


def main() -> int:
    args = _parse_args()
    report_path = Path(str(args.report)).resolve()
    if not report_path.is_file():
        payload = {
            "ok": False,
            "issues": [f"report_not_found:{report_path}"],
            "report": str(report_path),
        }
        text = json.dumps(payload, indent=2, ensure_ascii=False)
        print(text)
        return 2

    report = _load_report(report_path)
    config = report.get("config") if isinstance(report.get("config"), dict) else {}
    expected_stream_loops = (
        int(args.expected_stream_loops)
        if int(args.expected_stream_loops) > 0
        else to_int(config.get("stream_loops"), default=0)
    )
    expected_stress_runs = (
        int(args.expected_stress_runs)
        if int(args.expected_stress_runs) > 0
        else to_int(config.get("stress_runs"), default=0)
    )

    issues: list[str] = []
    if not bool(report.get("ok")):
        issues.append("report.ok is false")

    max_drift_pct = {
        "p50_ms": float(args.max_p50_drift_pct),
        "p95_ms": float(args.max_p95_drift_pct),
        "p99_ms": float(args.max_p99_drift_pct),
    }
    stream_summary = _validate_stream(
        stream=report.get("stream_gate") if isinstance(report.get("stream_gate"), dict) else {},
        expected_loops=expected_stream_loops,
        issues=issues,
    )
    stress_summary = _validate_stress(
        stress=report.get("stress") if isinstance(report.get("stress"), dict) else {},
        expected_runs=expected_stress_runs,
        max_error_rate_percent=float(args.max_error_rate_percent),
        max_drift_pct=max_drift_pct,
        issues=issues,
    )

    result = {
        "ok": len(issues) == 0,
        "report": str(report_path),
        "issues": issues,
        "summary": {
            "expected_stream_loops": expected_stream_loops,
            "expected_stress_runs": expected_stress_runs,
            "stream": stream_summary,
            "stress": stress_summary,
        },
    }
    text = json.dumps(result, indent=2, ensure_ascii=False)
    print(text)
    if str(args.out or "").strip():
        out_path = Path(str(args.out)).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text + "\n", encoding="utf-8")
    return 0 if result["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
