from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Protocol

from orket.core.contracts.decision_inputs import (
    FailureEvaluationInput,
    GuardReviewInput,
    LoopPolicyInputs,
    PlanningCardInput,
    PlanningInput,
    RoutingInput,
    SandboxComposeInput,
    SandboxPortInput,
    SeatPolicyInput,
    SuccessEvaluationInput,
    ToolSelectionInput,
)
from orket.core.contracts.model_selection import ModelSelectionInput


class PlannerNode(Protocol):
    """Decision node: determines which issues are candidates this tick."""

    def plan(self, data: PlanningInput) -> list[PlanningCardInput]: ...


class RouterNode(Protocol):
    """Decision node: determines which seat should execute an issue."""

    def route(self, data: RoutingInput) -> str: ...


class EvaluatorNode(Protocol):
    """Decision node: evaluates issue outcomes and quality signals."""

    def evaluate_success(self, inputs: SuccessEvaluationInput) -> Mapping[str, Any]: ...

    def evaluate_failure(self, inputs: FailureEvaluationInput) -> Mapping[str, Any]: ...

    def success_post_actions(self, success_eval: Mapping[str, Any]) -> Mapping[str, Any]: ...

    def should_trigger_sandbox(self, success_actions: Mapping[str, Any]) -> bool: ...

    def next_status_after_success(self, success_actions: Mapping[str, Any]) -> Any: ...

    def status_for_failure_action(self, action: str) -> Any: ...

    def should_cancel_session(self, action: str) -> bool: ...

    def failure_event_name(self, action: str) -> str | None: ...

    def governance_violation_message(self, error: str | None) -> str: ...

    def catastrophic_failure_message(self, issue_id: str, max_retries: int) -> str: ...

    def unexpected_failure_action_message(self, action: str, issue_id: str) -> str: ...

    def retry_failure_message(
        self,
        issue_id: str,
        retry_count: int,
        max_retries: int,
        error: str | None,
    ) -> str: ...

    def failure_exception_class(self, action: str) -> Any: ...


class PromptStrategyNode(Protocol):
    """Decision node: chooses model and dialect strategy for a turn."""

    def select_model(self, inputs: ModelSelectionInput) -> str: ...

    def select_dialect(self, model: str) -> str: ...


class ToolStrategyNode(Protocol):
    """Decision node: selects immutable names from application-owned bindings."""

    def select_tools(self, inputs: ToolSelectionInput) -> tuple[str, ...]: ...


class ApiRuntimeStrategyNode(Protocol):
    """Decision node: runtime-variable API choices."""

    def resolve_asset_id(self, path: str | None, issue_id: str | None) -> str | None: ...

    def resolve_run_active_invocation(
        self,
        asset_id: str,
        build_id: str | None,
        session_id: str,
        request_type: str | None,
    ) -> dict[str, Any]: ...

    def run_active_missing_asset_detail(self) -> str: ...

    def resolve_runs_invocation(self) -> dict[str, Any]: ...

    def resolve_backlog_invocation(self, session_id: str) -> dict[str, Any]: ...

    def resolve_session_detail_invocation(self, session_id: str) -> dict[str, Any]: ...

    def session_detail_not_found_error(self, session_id: str) -> dict[str, Any]: ...

    def resolve_session_snapshot_invocation(self, session_id: str) -> dict[str, Any]: ...

    def session_snapshot_not_found_error(self, session_id: str) -> dict[str, Any]: ...

    def resolve_sandboxes_list_invocation(self) -> dict[str, Any]: ...

    def resolve_sandbox_stop_invocation(self, sandbox_id: str) -> dict[str, Any]: ...

    def resolve_clear_logs_path(self) -> str: ...

    def resolve_clear_logs_invocation(self, log_path: str) -> dict[str, Any]: ...

    def resolve_read_invocation(self, path: str) -> dict[str, Any]: ...

    def read_not_found_detail(self, path: str) -> str: ...

    def permission_denied_detail(self, operation: str, error: str) -> str: ...

    def resolve_save_invocation(self, path: str, content: str) -> dict[str, Any]: ...

    def normalize_metrics(self, snapshot: dict[str, Any]) -> dict[str, Any]: ...

    def calendar_window(self, now: Any) -> dict[str, str]: ...

    def include_explorer_entry(self, entry_name: str) -> bool: ...

    def sort_explorer_items(self, items: list[dict[str, Any]]) -> list[dict[str, Any]]: ...

    def resolve_preview_target(self, path: str, issue_id: str | None) -> dict[str, str]: ...

    def select_preview_build_method(self, mode: str) -> str: ...

    def resolve_preview_invocation(self, target: dict[str, str], issue_id: str | None) -> dict[str, Any]: ...

    def preview_unsupported_detail(self, target: dict[str, str], invocation: dict[str, Any]) -> str: ...

    def resolve_chat_driver_invocation(self, message: str) -> dict[str, Any]: ...

    def resolve_sandbox_workspace(self, project_root: Any) -> Any: ...

    def resolve_sandbox_logs_invocation(self, sandbox_id: str, service: str | None) -> dict[str, Any]: ...

    def resolve_api_workspace(self, project_root: Any) -> Any: ...

    def should_remove_websocket(self, exception: Exception) -> bool: ...

    def has_archive_selector(
        self,
        card_ids: list[str] | None,
        build_id: str | None,
        related_tokens: list[str] | None,
    ) -> bool: ...

    def archive_selector_missing_detail(self) -> str: ...

    def normalize_archive_response(
        self,
        archived_ids: list[str],
        missing_ids: list[str],
        archived_count: int,
    ) -> dict[str, Any]: ...


class SandboxPolicyNode(Protocol):
    """Decision node: sandbox lifecycle policy choices."""

    def build_sandbox_id(self, rock_id: str) -> str: ...

    def build_compose_project(self, sandbox_id: str) -> str: ...

    def get_database_url(self, tech_stack: str, ports: SandboxPortInput, db_password: str = "") -> str: ...

    def generate_compose_file(self, sandbox: SandboxComposeInput, db_password: str, admin_password: str) -> str: ...


class LoaderStrategyNode(Protocol):
    """Decision node: config/model loader path and override policy."""

    def organization_modular_paths(self, config_dir: Any) -> tuple[Any, Any]: ...

    def organization_fallback_paths(self, config_dir: Any, model_dir: Any) -> list[Any]: ...

    def department_paths(self, config_dir: Any, model_dir: Any, name: str) -> list[Any]: ...

    def asset_paths(self, config_dir: Any, model_dir: Any, dept: str, category: str, name: str) -> list[Any]: ...

    def list_asset_search_paths(self, config_dir: Any, model_dir: Any, dept: str, category: str) -> list[Any]: ...



class ExecutionRuntimeStrategyNode(Protocol):
    """Decision node: execution runtime id/build selection policy."""

    def select_run_id(self, session_id: str | None) -> str: ...

    def select_epic_build_id(self, build_id: str | None, epic_name: str, sanitize_name: Any) -> str: ...

    def select_epic_collection_session_id(self, session_id: str | None) -> str: ...

    def select_epic_collection_build_id(
        self, build_id: str | None, collection_name: str, sanitize_name: Any
    ) -> str: ...
class OrchestrationLoopPolicyNode(Protocol):
    """Decision node: execution-loop policy knobs for orchestrator runtime."""

    def concurrency_limit(self, inputs: LoopPolicyInputs) -> int: ...

    def max_iterations(self, inputs: LoopPolicyInputs) -> int: ...

    def context_window(self, inputs: LoopPolicyInputs) -> int: ...

    def is_review_turn(self, issue_status: Any) -> bool: ...

    def turn_status_for_issue(self, is_review_turn: bool) -> Any: ...

    def role_order_for_turn(self, roles: tuple[str, ...], is_review_turn: bool) -> list[str]: ...

    def required_action_tools_for_seat(self, inputs: SeatPolicyInput) -> list[str]: ...

    def required_statuses_for_seat(self, inputs: SeatPolicyInput) -> list[str]: ...

    def required_read_paths_for_seat(self, inputs: SeatPolicyInput) -> list[str]: ...

    def required_write_paths_for_seat(self, inputs: SeatPolicyInput) -> list[str]: ...

    def gate_mode_for_seat(self, inputs: SeatPolicyInput) -> str: ...

    def approval_required_tools_for_seat(self, inputs: SeatPolicyInput) -> list[str]: ...

    def validate_guard_rejection_payload(self, inputs: GuardReviewInput) -> Mapping[str, Any]: ...

    def missing_seat_status(self) -> Any: ...

    def is_backlog_done(self, backlog: tuple[PlanningCardInput, ...]) -> bool: ...

    def no_candidate_outcome(self, backlog: tuple[PlanningCardInput, ...]) -> dict[str, Any]: ...

    def should_raise_exhaustion(
        self,
        iteration_count: int,
        max_iterations: int,
        backlog: tuple[PlanningCardInput, ...],
    ) -> bool: ...
