name: Orket Sentinel

on:
  push:
  pull_request:

jobs:
  sentinel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure full git history
        run: git fetch --all --tags --prune || true

      - name: Run Orket Sentinel
        env:
          TRIPLELOCK_ROOTS: data/dto
          LOG_FORMAT_VERSION: "2"
        run: python3 tools/ci/orket_sentinel.py
