name: Quality

on:
  push:
    branches: [main]
  pull_request:

jobs:
  architecture_gates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"

      - name: Enforce dependency direction rules
        run: |
          python scripts/check_dependency_direction.py

      - name: Enforce volatility boundary script
        run: |
          python scripts/check_volatility_boundaries.py

      - name: Enforce volatility boundary tests
        run: |
          python -m pytest -q tests/platform/test_architecture_volatility_boundaries.py

      - name: Enforce roadmap metrics (quick gate)
        run: |
          python scripts/check_roadmap_metrics.py --quick

      - name: Validate prompt assets
        run: |
          python -m orket.interfaces.prompts_cli --root . validate --json

      - name: Smoke resolve canonical prompt
        run: |
          python -m orket.interfaces.prompts_cli --root . resolve --role architect --dialect generic --selection-policy stable

      - name: Smoke diff prompt policies
        run: |
          python -m orket.interfaces.prompts_cli --root . diff --role architect --dialect generic --left-policy stable --right-policy canary

      - name: Enforce line-ending normalization
        run: |
          git add --renormalize .
          if ! git diff --cached --quiet; then
            echo "Line ending normalization drift detected:"
            git diff --cached --name-only
            exit 1
          fi

  quality:
    runs-on: ubuntu-latest
    needs: architecture_gates
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"

      - name: Run tests with coverage
        run: pytest tests/ --cov=orket --cov-fail-under=60

      - name: Ruff lint
        run: ruff check orket/

      - name: Mypy type check
        run: mypy orket/ --ignore-missing-imports

      - name: Enforce datetime.now UTC usage
        run: |
          if grep -R --line-number "datetime.now()" orket --include="*.py" | grep -v "now(UTC)"; then
            echo "Found disallowed datetime.now() usage"
            exit 1
          fi

      - name: Enforce dependency direction rules
        run: |
          python scripts/check_dependency_direction.py

      - name: Enforce volatility boundary script
        run: |
          python scripts/check_volatility_boundaries.py

      - name: Enforce roadmap pytest metrics
        run: |
          python scripts/check_roadmap_metrics.py

      - name: Build monolith variant matrix plan
        run: |
          python scripts/run_monolith_variant_matrix.py --out benchmarks/results/monolith_variant_matrix.json

      - name: Enforce monolith readiness gate policy
        run: |
          python scripts/check_monolith_readiness_gate.py --matrix benchmarks/results/monolith_variant_matrix.json --policy model/core/contracts/monolith_readiness_policy.json --allow-plan-only

      - name: Evaluate microservices unlock checklist
        run: |
          python scripts/check_microservices_unlock.py --matrix benchmarks/results/monolith_variant_matrix.json --readiness-policy model/core/contracts/monolith_readiness_policy.json --unlock-policy model/core/contracts/microservices_unlock_policy.json --live-report benchmarks/results/live_acceptance_patterns.json --out benchmarks/results/microservices_unlock_check.json

      - name: Build architecture pilot matrix plan
        run: |
          python scripts/run_architecture_pilot_matrix.py --out benchmarks/results/architecture_pilot_matrix.json

      - name: Validate prompt assets
        run: |
          python -m orket.interfaces.prompts_cli --root . validate --json

      - name: Smoke resolve canonical prompt
        run: |
          python -m orket.interfaces.prompts_cli --root . resolve --role architect --dialect generic --selection-policy stable

      - name: Enforce line-ending normalization
        run: |
          git add --renormalize .
          if ! git diff --cached --quiet; then
            echo "Line ending normalization drift detected:"
            git diff --cached --name-only
            exit 1
          fi

      - name: Upload load evidence artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: load-evidence-${{ github.run_id }}
          path: benchmarks/results/*.json
          if-no-files-found: warn

  product_quality:
    runs-on: ubuntu-latest
    needs: architecture_gates
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"

      - name: Run product suite (explicit scope when present)
        run: |
          if [ -d "product/sneaky_price_watch/tests" ]; then
            PYTHONPATH=product/sneaky_price_watch pytest product/sneaky_price_watch/tests -q
          else
            echo "product/sneaky_price_watch/tests not present; suite intentionally excluded."
          fi

  docker_smoke:
    runs-on: ubuntu-latest
    needs: [quality, product_quality]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t orket:${{ github.sha }} .

      - name: Start container
        run: |
          docker run -d --name orket-smoke -p 8082:8082 orket:${{ github.sha }}

      - name: Probe health endpoint
        run: |
          for i in $(seq 1 30); do
            if curl -sf http://127.0.0.1:8082/health >/dev/null; then
              echo "Health probe succeeded"
              exit 0
            fi
            sleep 2
          done
          echo "Health probe failed"
          docker logs orket-smoke || true
          exit 1

      - name: Cleanup container
        if: always()
        run: |
          docker rm -f orket-smoke || true

  migration_smoke:
    runs-on: ubuntu-latest
    needs: [quality, product_quality]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"

      - name: Bootstrap runtime/webhook schemas
        run: |
          python - <<'PY'
          import asyncio
          from pathlib import Path
          from orket.infrastructure.async_card_repository import AsyncCardRepository
          from orket.services.webhook_db import WebhookDatabase

          async def main():
              repo = AsyncCardRepository(".ci/runtime.db")
              await repo.get_by_build("_migration_smoke_bootstrap_")
              webhook = WebhookDatabase(Path(".ci/webhook.db"))
              await webhook.get_active_prs()

          asyncio.run(main())
          print("Schema bootstrap completed")
          PY

      - name: Run migration smoke
        run: |
          python scripts/run_migrations.py --runtime-db .ci/runtime.db --webhook-db .ci/webhook.db

      - name: Validate migration tables
        run: |
          python - <<'PY'
          import sqlite3
          for db in [".ci/runtime.db", ".ci/webhook.db"]:
              conn = sqlite3.connect(db)
              cur = conn.cursor()
              cur.execute("SELECT COUNT(*) FROM _schema_migrations")
              count = cur.fetchone()[0]
              if count < 1:
                  raise SystemExit(f"No migrations recorded for {db}")
              conn.close()
          print("Migration smoke validation passed")
          PY
