name: Quant Sweep Smoke

on:
  pull_request:
    paths:
      - "scripts/run_quant_sweep.py"
      - "scripts/run_determinism_harness.py"
      - "scripts/live_card_benchmark_runner.py"
      - "scripts/manage_baselines.py"
      - "scripts/check_quant_sweep_kpis.py"
      - "scripts/quant_sweep_kpi_report.py"
      - "scripts/sidecar_probe.py"
      - "scripts/quant_frontier_explorer.py"
      - "scripts/context_ceiling_finder.py"
      - "scripts/thermal_stability_profiler.py"
      - "scripts/check_explorer_schema_contracts.py"
      - "scripts/check_lab_guards.py"
      - "scripts/run_context_sweep.py"
      - "scripts/check_context_sweep_outputs.py"
      - "scripts/build_explorer_artifact_index.py"
      - "scripts/check_explorer_ingestion.py"
      - "scripts/build_context_sweep_rollup.py"
      - "scripts/check_context_rollup_contract.py"
      - "scripts/cleanup_context_sweep_artifacts.py"
      - "scripts/check_context_profile_policy.py"
      - "scripts/build_explorer_check_summary.py"
      - "scripts/render_explorer_check_digest.py"
      - "tests/application/test_quant_sweep_runner.py"
      - "tests/application/test_manage_baselines_script.py"
      - "tests/application/test_benchmark_telemetry_manifest.py"
      - "tests/application/test_quant_sweep_kpi_scripts.py"
      - "tests/application/test_quant_frontier_explorer.py"
      - "tests/application/test_context_ceiling_finder.py"
      - "tests/application/test_thermal_stability_profiler.py"
      - "tests/application/test_explorer_schema_contracts.py"
      - "tests/application/test_lab_guard_checker.py"
      - "tests/application/test_run_context_sweep.py"
      - "tests/application/test_context_sweep_output_contracts.py"
      - "tests/application/test_build_explorer_artifact_index.py"
      - "tests/application/test_check_explorer_ingestion.py"
      - "tests/fixtures/explorer_index/valid_index.json"
      - "tests/fixtures/explorer_index/invalid_missing_kind.json"
      - "tests/application/test_build_context_sweep_rollup.py"
      - "tests/application/test_context_rollup_contract.py"
      - "tests/application/test_cleanup_context_sweep_artifacts.py"
      - "tests/application/test_check_context_profile_policy.py"
      - "tests/fixtures/context_profiles/valid_profiles.json"
      - "tests/fixtures/context_profiles/drifted_profiles.json"
      - "tests/application/test_build_explorer_check_summary.py"
      - "tests/application/test_render_explorer_check_digest.py"
      - "benchmarks/configs/quant_sweep_common_sessions.json"
      - "benchmarks/configs/quant_sweep_logic_only.json"
      - "benchmarks/configs/quant_sweep_refactor_heavy.json"
      - "benchmarks/configs/quant_sweep_mixed.json"
      - "benchmarks/configs/context_sweep_profiles.json"
      - "benchmarks/configs/sidecar_profiles.json"
      - "docs/QUANT_SWEEP_RUNBOOK.md"
      - ".gitea/workflows/quant-sweep-smoke.yml"
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Quant Sweep Unit Coverage
        run: |
          python -m pytest \
            tests/application/test_quant_sweep_runner.py \
            tests/application/test_manage_baselines_script.py \
            tests/application/test_benchmark_telemetry_manifest.py \
            tests/application/test_quant_sweep_kpi_scripts.py \
            tests/application/test_quant_frontier_explorer.py \
            tests/application/test_context_ceiling_finder.py \
            tests/application/test_thermal_stability_profiler.py \
            tests/application/test_explorer_schema_contracts.py \
            tests/application/test_lab_guard_checker.py \
            tests/application/test_run_context_sweep.py \
            tests/application/test_context_sweep_output_contracts.py \
            tests/application/test_build_explorer_artifact_index.py \
            tests/application/test_check_explorer_ingestion.py \
            tests/application/test_build_context_sweep_rollup.py \
            tests/application/test_context_rollup_contract.py \
            tests/application/test_cleanup_context_sweep_artifacts.py \
            tests/application/test_check_context_profile_policy.py \
            tests/application/test_build_explorer_check_summary.py \
            tests/application/test_render_explorer_check_digest.py -q

      - name: Matrix Dry Run Smoke
        run: |
          python scripts/run_quant_sweep.py \
            --model-id placeholder-model \
            --quant-tags Q8_0 \
            --matrix-config benchmarks/configs/quant_sweep_common_sessions.json \
            --dry-run
