name: Quant Sweep Nightly

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
    inputs:
      matrix_config:
        description: "Matrix config path"
        required: false
        default: "benchmarks/configs/quant_sweep_common_sessions.json"
      task_limit:
        description: "Optional task limit for hosted smoke"
        required: false
        default: "1"

jobs:
  hosted-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Quant Sweep Dry Run
        run: |
          python scripts/run_quant_sweep.py \
            --model-id placeholder-model \
            --quant-tags Q8_0 \
            --matrix-config "${{ github.event.inputs.matrix_config || 'benchmarks/configs/quant_sweep_common_sessions.json' }}" \
            --task-limit "${{ github.event.inputs.task_limit || '1' }}" \
            --dry-run

      - name: Build KPI Sample Artifact
        run: |
          python - <<'PY'
          import json
          from pathlib import Path
          path = Path("benchmarks/results/quant_sweep/nightly_sample_summary.json")
          path.parent.mkdir(parents=True, exist_ok=True)
          payload = {
              "schema_version": "1.1.3",
              "stability_kpis": {
                  "determinism_rate": 1.0,
                  "missing_telemetry_rate": 0.0,
                  "polluted_run_rate": 0.0,
                  "frontier_success_rate": 1.0,
                  "quant_rows": 1,
                  "sessions": 1,
                  "weighted_runs": 1
              }
          }
          path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
          PY

      - name: Extract KPI Report
        run: |
          python scripts/quant_sweep_kpi_report.py \
            --summary benchmarks/results/quant_sweep/nightly_sample_summary.json \
            --out benchmarks/results/quant_sweep/nightly_sample_kpis.json

      - name: Enforce KPI Thresholds
        run: |
          python scripts/check_quant_sweep_kpis.py \
            --summary benchmarks/results/quant_sweep/nightly_sample_summary.json \
            --max-missing-telemetry-rate 0.01 \
            --max-polluted-run-rate 0.1 \
            --min-frontier-success-rate 0.8 \
            --min-determinism-rate 1.0

      - name: Upload Quant Sweep Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quant-sweep-nightly-artifacts
          path: |
            benchmarks/results/quant_sweep/nightly_sample_summary.json
            benchmarks/results/quant_sweep/nightly_sample_kpis.json
