from __future__ import annotations

import asyncio
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping


@dataclass(frozen=True)
class DependencySpec:
    required_files: Dict[str, str]


class DependencyValidationError(Exception):
    """Raised when dependency stage validation fails."""


class DependencyManager:
    """
    Deterministic dependency stage.

    Owns dependency-manifest baseline files for generated projects.
    """

    _DEFAULT_FILES: Dict[str, str] = {
        "agent_output/dependencies/pyproject.toml": (
            "[project]\n"
            "name = \"orket-generated-project\"\n"
            "version = \"0.1.0\"\n"
            "description = \"Generated by Orket\"\n"
            "requires-python = \">=3.11\"\n"
            "dependencies = []\n"
        ),
        "agent_output/dependencies/requirements.txt": "",
        "agent_output/dependencies/package.json": (
            "{\n"
            "  \"name\": \"orket-generated-project\",\n"
            "  \"version\": \"0.1.0\",\n"
            "  \"private\": true,\n"
            "  \"scripts\": {\n"
            "    \"build\": \"echo build-not-configured\"\n"
            "  }\n"
            "}\n"
        ),
    }

    def __init__(self, workspace_root: Path, file_tools: Any, organization: Any = None):
        self.workspace_root = workspace_root
        self.file_tools = file_tools
        self.organization = organization

    async def ensure(self) -> Dict[str, Any]:
        spec = self._resolve_spec()
        created_files = await self._ensure_files(spec.required_files)
        await self._validate_required_files(spec.required_files)
        return {
            "created_files": created_files,
            "required_files": sorted(spec.required_files.keys()),
        }

    def _resolve_spec(self) -> DependencySpec:
        rules = {}
        if self.organization and isinstance(getattr(self.organization, "process_rules", None), dict):
            rules = self.organization.process_rules
        required_files = self._normalize_file_map(
            rules.get("dependency_manager_required_files"),
            self._DEFAULT_FILES,
        )
        return DependencySpec(required_files=dict(required_files))

    async def _ensure_files(self, required_files: Mapping[str, str]) -> List[str]:
        created: List[str] = []
        for rel_path, content in required_files.items():
            target = self.workspace_root / rel_path
            exists = await asyncio.to_thread(target.exists)
            if exists:
                continue
            await self.file_tools.write_file(rel_path, content)
            created.append(rel_path)
        return created

    async def _validate_required_files(self, required_files: Mapping[str, str]) -> None:
        missing = []
        for rel_path in required_files.keys():
            exists = await asyncio.to_thread((self.workspace_root / rel_path).is_file)
            if not exists:
                missing.append(rel_path)
        if missing:
            raise DependencyValidationError(
                "missing dependency files: " + ", ".join(sorted(missing))
            )

    @staticmethod
    def _normalize_file_map(raw: Any, default: Mapping[str, str]) -> Dict[str, str]:
        if isinstance(raw, dict):
            normalized = {}
            for key, value in raw.items():
                key_str = str(key).strip()
                if not key_str:
                    continue
                normalized[key_str] = str(value)
            if normalized:
                return normalized
        return dict(default)

