"""Pure operator resource templates and legacy epic normalization."""
import re
from typing import Any


def normalize_epic(epic_data: dict[str, Any]) -> tuple[dict[str, Any], bool]:
    issues = epic_data.get("issues")
    if isinstance(issues, list):
        epic_data.pop("cards", None)
        return epic_data, False
    cards = epic_data.pop("cards", None)
    epic_data["issues"] = list(cards) if isinstance(cards, list) else []
    return epic_data, isinstance(cards, list)


def _slug_name(value: str) -> str:
    return re.sub(r"[^a-z0-9_]+", "_", str(value or "").strip().lower()).strip("_") or "unnamed"

def _team_template(name: str) -> dict[str, Any]:
    return {
        "name": name,
        "description": f"Team '{name}' generated by Operator CLI.",
        "roles": {
            "coder": {
                "name": "coder",
                "description": "Software Engineer role focusing on implementation.",
                "tools": [
                    "read_file",
                    "write_file",
                    "list_directory",
                    "add_issue_comment",
                    "get_issue_context",
                    "update_issue_status",
                ],
            },
            "code_reviewer": {
                "name": "code_reviewer",
                "description": "Code reviewer role for governance and quality review.",
                "tools": [
                    "read_file",
                    "list_directory",
                    "add_issue_comment",
                    "get_issue_context",
                    "update_issue_status",
                ],
            },
            "integrity_guard": {
                "name": "integrity_guard",
                "description": "Guard review role for final runtime and governance validation.",
                "tools": ["read_file", "list_directory", "get_issue_context", "update_issue_status"],
            },
        },
        "seats": {
            "coder": {"name": "Coder", "roles": ["coder"]},
            "code_reviewer": {"name": "Code Reviewer", "roles": ["code_reviewer"]},
            "integrity_guard": {"name": "Integrity Guard", "roles": ["integrity_guard"]},
        },
    }

def _environment_template(name: str) -> dict[str, Any]:
    return {
        "name": name,
        "description": f"Environment '{name}' generated by Operator CLI.",
        "model": "qwen3-coder:latest",
        "temperature": 0.2,
        "seed": 42,
        "params": {},
    }

def _epic_template(name: str) -> dict[str, Any]:
    return {
        "name": name,
        "description": f"Epic '{name}' generated by Operator CLI.",
        "team": "standard",
        "environment": "standard",
        "issues": [],
    }

def _rock_template(name: str, department: str) -> dict[str, Any]:
    rock_id = f"{_slug_name(name).upper()}-ROCK"
    return {
        "id": rock_id,
        "name": name,
        "description": f"Rock '{name}' generated by Operator CLI.",
        "status": "active",
        "owner_department": department,
        "epics": [],
    }
